version: '3.1'

services:

  mongo:
    image: mongo:7.0.4
    container_name: strava-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - volume-strava-db:/data/db

volumes:
  volume-strava-db:
    external: true
